#ifndef FN_DATA_H
#define FN_DATA_H

#define FUJICMD_RESET "\xFF"
#define FUJICMD_GET_SSID "\xFE"
#define FUJICMD_SCAN_NETWORKS "\xFD"
#define FUJICMD_GET_SCAN_RESULT "\xFC"
#define FUJICMD_SET_SSID "\xFB"
#define FUJICMD_GET_WIFISTATUS "\xFA"
#define FUJICMD_MOUNT_HOST "\xF9"
#define FUJICMD_MOUNT_IMAGE "\xF8"
#define FUJICMD_OPEN_DIRECTORY "\xF7"
#define FUJICMD_READ_DIR_ENTRY "\xF6"
#define FUJICMD_CLOSE_DIRECTORY "\xF5"
#define FUJICMD_READ_HOST_SLOTS "\xF4"
#define FUJICMD_WRITE_HOST_SLOTS "\xF3"
#define FUJICMD_READ_DEVICE_SLOTS "\xF2"
#define FUJICMD_WRITE_DEVICE_SLOTS "\xF1"
#define FUJICMD_UNMOUNT_IMAGE "\xE9"
#define FUJICMD_GET_ADAPTERCONFIG "\xE8"
#define FUJICMD_NEW_DISK "\xE7"
#define FUJICMD_UNMOUNT_HOST "\xE6"
#define FUJICMD_GET_DIRECTORY_POSITION "\xE5"
#define FUJICMD_SET_DIRECTORY_POSITION "\xE4"
#define FUJICMD_SET_DEVICE_FULLPATH "\xE2"
#define FUJICMD_SET_HOST_PREFIX "\xE1"
#define FUJICMD_GET_HOST_PREFIX "\xE0"
#define FUJICMD_WRITE_APPKEY "\xDE"
#define FUJICMD_READ_APPKEY "\xDD"
#define FUJICMD_OPEN_APPKEY "\xDC"
#define FUJICMD_CLOSE_APPKEY "\xDB"
#define FUJICMD_GET_DEVICE_FULLPATH "\xDA"
#define FUJICMD_CONFIG_BOOT "\xD9"
#define FUJICMD_COPY_FILE "\xD8"
#define FUJICMD_MOUNT_ALL "\xD7"
#define FUJICMD_SET_BOOT_MODE "\xD6"
#define FUJICMD_ENABLE_DEVICE "\xD5"
#define FUJICMD_DISABLE_DEVICE "\xD4"
#define FUJICMD_DEVICE_STATUS "\xD1"
#define FUJICMD_STATUS "\x53"

#define LFN 15
#define DEV 15
#define SAN 15

// Generic buffer used by number of implementations
extern char response[1024];

#endif /* FN_DATA_H */