#ifndef FUJINET_COMMAND_H
#define FUJINET_COMMAND_H

enum {
  FUJICMD_RESET                         = 0xFF,
  FUJICMD_PASSWORD                      = 0xFE,
  FUJICMD_GET_SSID                      = 0xFE,
  FUJICMD_USERNAME                      = 0xFD,
  FUJICMD_SCAN_NETWORKS                 = 0xFD,
  FUJICMD_JSON_MODE                     = 0xFC,
  FUJICMD_GET_SCAN_RESULT               = 0xFC,
  FUJICMD_SET_SSID                      = 0xFB,
  FUJICMD_GET_WIFISTATUS                = 0xFA,
  FUJICMD_MOUNT_HOST                    = 0xF9,
  FUJICMD_MOUNT_IMAGE                   = 0xF8,
  FUJICMD_OPEN_DIRECTORY                = 0xF7,
  FUJICMD_READ_DIR_ENTRY                = 0xF6,
  FUJICMD_CLOSE_DIRECTORY               = 0xF5,
  FUJICMD_READ_HOST_SLOTS               = 0xF4,
  FUJICMD_WRITE_HOST_SLOTS              = 0xF3,
  FUJICMD_READ_DEVICE_SLOTS             = 0xF2,
  FUJICMD_WRITE_DEVICE_SLOTS            = 0xF1,
  FUJICMD_GET_WIFI_ENABLED              = 0xEA,
  FUJICMD_UNMOUNT_IMAGE                 = 0xE9,
  FUJICMD_GET_ADAPTERCONFIG             = 0xE8,
  FUJICMD_NEW_DISK                      = 0xE7,
  FUJICMD_UNMOUNT_HOST                  = 0xE6,
  FUJICMD_GET_DIRECTORY_POSITION        = 0xE5,
  FUJICMD_SET_DIRECTORY_POSITION        = 0xE4,
  FUJICMD_SET_DEVICE_FULLPATH           = 0xE2,
  FUJICMD_SET_HOST_PREFIX               = 0xE1,
  FUJICMD_GET_HOST_PREFIX               = 0xE0,
  FUJICMD_WRITE_APPKEY                  = 0xDE,
  FUJICMD_READ_APPKEY                   = 0xDD,
  FUJICMD_OPEN_APPKEY                   = 0xDC,
  FUJICMD_CLOSE_APPKEY                  = 0xDB,
  FUJICMD_GET_DEVICE_FULLPATH           = 0xDA,
  FUJICMD_CONFIG_BOOT                   = 0xD9,
  FUJICMD_COPY_FILE                     = 0xD8,
  FUJICMD_MOUNT_ALL                     = 0xD7,
  FUJICMD_SET_BOOT_MODE                 = 0xD6,
  FUJICMD_ENABLE_DEVICE                 = 0xD5,
  FUJICMD_DISABLE_DEVICE                = 0xD4,
  FUJICMD_RANDOM_NUMBER                 = 0xD3,
  FUJICMD_GET_TIME                      = 0xD2,
  FUJICMD_DEVICE_ENABLE_STATUS          = 0xD1,
  FUJICMD_BASE64_ENCODE_INPUT           = 0xD0,
  FUJICMD_BASE64_ENCODE_COMPUTE         = 0xCF,
  FUJICMD_BASE64_ENCODE_LENGTH          = 0xCE,
  FUJICMD_BASE64_ENCODE_OUTPUT          = 0xCD,
  FUJICMD_BASE64_DECODE_INPUT           = 0xCC,
  FUJICMD_BASE64_DECODE_COMPUTE         = 0xCB,
  FUJICMD_BASE64_DECODE_LENGTH          = 0xCA,
  FUJICMD_BASE64_DECODE_OUTPUT          = 0xC9,
  FUJICMD_HASH_INPUT                    = 0xC8,
  FUJICMD_HASH_COMPUTE                  = 0xC7,
  FUJICMD_HASH_LENGTH                   = 0xC6,
  FUJICMD_HASH_OUTPUT                   = 0xC5,
  FUJICMD_GET_ADAPTERCONFIG_EXTENDED    = 0xC4,
  FUJICMD_HASH_COMPUTE_NO_CLEAR         = 0xC3,
  FUJICMD_HASH_CLEAR                    = 0xC2,
  FUJICMD_GENERATE_GUID                 = 0xBB,
  FUJICMD_GET_DEVICE1_FULLPATH          = 0xA0,
  FUJICMD_SET_STATUS                    = 0x81,
  FUJICMD_WRITE                         = 0x57,
  FUJICMD_STATUS                        = 0x53,
  FUJICMD_READ                          = 0x52,
  FUJICMD_QUERY                         = 0x51,
  FUJICMD_PARSE                         = 0x50,
  FUJICMD_OPEN                          = 0x4F,
  FUJICMD_SET_MODE                      = 0x4D,
  FUJICMD_CLOSE                         = 0x43,
  FUJICMD_ACCEPT                        = 0x41,
  FUJICMD_GETCWD                        = 0x30,
  FUJICMD_CHDIR                         = 0x2C,
  FUJICMD_RMDIR                         = 0x2B,
  FUJICMD_MKDIR                         = 0x2A,
  FUJICMD_TELL                          = 0x26,
  FUJICMD_SEEK                          = 0x25,
  FUJICMD_DELETE                        = 0x21,
  FUJICMD_RENAME                        = 0x20,

  APETIMECMD_GETTZTIME                  = 0x9A,
  APETIMECMD_SETTZ                      = 0x99,
  APETIMECMD_GETTIME                    = 0x93,
  APETIMECMD_GET_ISO_UTC_ALT            = 0x7A, // z
  APETIMECMD_SETTZ_ALT                  = 0x74, // t
  APETIMECMD_GET_SOS_ALT                = 0x73, // s
  APETIMECMD_GET_PRODOS_ALT             = 0x70, // p
  APETIMECMD_GET_ISO_LOCAL_ALT          = 0x69, // i
  APETIMECMD_GET_ATARI_ALT              = 0x61, // a
  APETIMECMD_GET_ISO_UTC                = 0x5A, // Z
  APETIMECMD_SETTZ_ALT2                 = 0x54, // T
  APETIMECMD_GET_SOS                    = 0x53, // S
  APETIMECMD_GET_PRODOS                 = 0x50, // P
  APETIMECMD_GETTZ_LEN                  = 0x4C, // L
  APETIMECMD_GET_ISO_LOCAL              = 0x49, // I
  APETIMECMD_GET_GENERAL                = 0x47, // G
  APETIMECMD_GET_ATARI                  = 0x41, // A
};

#endif /* FUJINET_COMMAND_H */
