# -*- indent-tabs-mode: nil; -*-

name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - adam
          - apple2
          - atari
          - c64
          - coco
          - lynx
          - model2
          - msdos
          - msx

    container:
      image: fozztexx/defoogi:1.4.8

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make ${{ matrix.platform }}/r2r

      # PR case: normal artifact upload
      - name: Upload artifact for ${{ matrix.platform }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: r2r/${{ matrix.platform }}/**

  check-no-build-ifdefs:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check for BUILD_ #ifdefs
        run: python3 testing/check_no_build_ifdefs.py common include

  compile-tests:
    needs: build
    runs-on: ubuntu-latest

    container:
      image: fozztexx/defoogi:1.4.8

    steps:
      - uses: actions/checkout@v4

      - name: Build lib
        run: make

      - name: Compile tests
        run: make -C testing
